version: '2'

services:
  clusterf-proxy:
    image: andymacdonald/clusterf-chaos-proxy
    environment:
      name: clusterf-proxy
      JAVA_OPTS: "-Dchaos.strategy=RANDOM_HAVOC -Ddestination.hostProtocolAndPort=http://database:3100 -Dchaos.strategy.delayResponse.random.maxSeconds=10"
    networks:
      - some-net
    ports:
    - "8088:8080"

  database:
    image: mitchallen/random-server
    networks:
      - some-net
    expose:
    - 3100

  uberserver:
    build: ../TRASK_uberserver-main (1)/TRASK_uberserver-main
    networks:
      - some-net
    ports:
    - "8000:8000"

networks:
  some-net:
    driver: bridge